---
#spring:
#  profiles: local-dev

#eureka:
#  client:
#    serviceUrl: http://localhost:8761/eureka
#  registerWithEureka: true
#  fetchRegistry: true
#  enabled: true
---
#spring:
#  profiles: docker

#eureka:
#  client:
#    serviceUrl: http://discovery:8761/eureka
#  registerWithEureka: true
#  fetchRegistry: true
#  enabled: true
